# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="events_event_code_5c18fe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("USER", "USER"),
                            ("ADMIN", "ADMIN"),
                            ("VENDOR", "VENDOR"),
                            ("SYSTEM", "SYSTEM"),
                            ("TELEGRAM", "TELEGRAM"),
                        ],
                        default="SYSTEM",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB", "WEB"),
                            ("MOBILE", "MOBILE"),
                            ("TELEGRAM", "TELEGRAM"),
                            ("ADMIN", "ADMIN"),
                            ("CRON", "CRON"),
                            ("BACKEND", "BACKEND"),
                        ],
                        default="BACKEND",
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="INFO",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="accounts.user",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.eventtype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="events_event_creat_63343d_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="events_event_event_t_77b6cf_idx",
                    ),
                    models.Index(
                        fields=["actor_type", "created_at"],
                        name="events_event_actor_t_6b2a15_idx",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="events_event_source__99ea27_idx",
                    ),
                    models.Index(
                        fields=["level", "created_at"],
                        name="events_event_level_c_68b2df_idx",
                    ),
                    models.Index(fields=["order"], name="events_event_order_id_32989b_idx"),
                    models.Index(fields=["vendor"], name="events_event_vendor_i_be0e74_idx"),
                ],
            },
        ),
    ]
