# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("vendors", "0001_initial"),
        ("addresses", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("WEB", "WEB"), ("TELEGRAM", "TELEGRAM"), ("ADMIN", "ADMIN")],
                        db_index=True,
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("PENDING_PAYMENT", "PENDING_PAYMENT"),
                            ("PLACED", "PLACED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PREPARING", "PREPARING"),
                            ("READY", "READY"),
                            ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                            ("DELIVERED", "DELIVERED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                        ],
                        db_index=True,
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                ("customer_note", models.CharField(blank=True, default="", max_length=400)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("subtotal_amount", models.BigIntegerField(default=0)),
                ("discount_amount", models.BigIntegerField(default=0)),
                ("delivery_fee_amount", models.BigIntegerField(default=0)),
                ("service_fee_amount", models.BigIntegerField(default=0)),
                ("total_amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="IRR", max_length=8)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "UNPAID"), ("PAID", "PAID"), ("REFUNDED", "REFUNDED"), ("FAILED", "FAILED")],
                        db_index=True,
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("ONLINE", "ONLINE"), ("COD", "COD")],
                        db_index=True,
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("placed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="addresses.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.user",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "status", "placed_at"],
                        name="orders_ord_vendor__cb7be6_idx",
                    ),
                    models.Index(fields=["user", "placed_at"], name="orders_ord_user_id_4a480c_idx"),
                    models.Index(fields=["source", "placed_at"], name="orders_ord_source__c35fe2_idx"),
                    models.Index(
                        fields=["payment_status", "placed_at"],
                        name="orders_ord_payment_449fc1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("IN_ZONE", "IN_ZONE"), ("OUT_OF_ZONE_SNAPP", "OUT_OF_ZONE_SNAPP")],
                        db_index=True,
                        default="IN_ZONE",
                        max_length=22,
                    ),
                ),
                ("is_cash_on_delivery", models.BooleanField(default=False)),
                ("courier_name", models.CharField(blank=True, default="", max_length=120)),
                ("courier_phone", models.CharField(blank=True, default="", max_length=32)),
                ("tracking_code", models.CharField(blank=True, default="", max_length=80)),
                ("tracking_url", models.URLField(blank=True, default="")),
                ("external_delivery_quote_amount", models.BigIntegerField(default=0)),
                ("external_delivery_final_amount", models.BigIntegerField(default=0)),
                ("external_provider", models.CharField(blank=True, default="", max_length=30)),
                ("external_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["delivery_type", "created_at"],
                        name="orders_ord_deliver_9e1b53_idx",
                    ),
                    models.Index(
                        fields=["external_provider"], name="orders_ord_external_a009ae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, default="", max_length=20)),
                ("to_status", models.CharField(db_index=True, max_length=20)),
                (
                    "changed_by_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "SYSTEM"),
                            ("CUSTOMER", "CUSTOMER"),
                            ("VENDOR", "VENDOR"),
                            ("ADMIN", "ADMIN"),
                        ],
                        db_index=True,
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=250)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to="accounts.user",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"],
                        name="orders_ord_order_i_84bba9_idx",
                    ),
                    models.Index(
                        fields=["to_status", "created_at"],
                        name="orders_ord_to_stat_6e6cf5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_title_snapshot", models.CharField(max_length=250)),
                ("unit_price_snapshot", models.BigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("modifiers", models.JSONField(blank=True, null=True)),
                ("line_subtotal", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["order", "created_at"],
                        name="orders_ord_order_i_b9425c_idx",
                    ),
                    models.Index(
                        fields=["product"], name="orders_ord_product_8031a9_idx"
                    ),
                ],
            },
        ),
    ]
