# Generated by hand to capture initial Order models with pending payment defaults.
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("catalog", "0002_product_menu_structure"),
        ("vendors", "0003_vendor_delivery_zones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("WEB", "WEB"), ("TELEGRAM", "TELEGRAM"), ("ADMIN", "ADMIN")],
                        db_index=True,
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("PENDING_PAYMENT", "PENDING_PAYMENT"),
                            ("PLACED", "PLACED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("PREPARING", "PREPARING"),
                            ("READY", "READY"),
                            ("OUT_FOR_DELIVERY", "OUT_FOR_DELIVERY"),
                            ("DELIVERED", "DELIVERED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                        ],
                        db_index=True,
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                ("customer_note", models.CharField(blank=True, default="", max_length=400)),
                ("admin_note", models.TextField(blank=True, default="")),
                ("subtotal_amount", models.BigIntegerField(default=0)),
                ("discount_amount", models.BigIntegerField(default=0)),
                ("delivery_fee_amount", models.BigIntegerField(default=0)),
                ("service_fee_amount", models.BigIntegerField(default=0)),
                ("total_amount", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="IRR", max_length=8)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "UNPAID"), ("PAID", "PAID"), ("REFUNDED", "REFUNDED"), ("FAILED", "FAILED")],
                        db_index=True,
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("ONLINE", "ONLINE"), ("COD", "COD")],
                        db_index=True,
                        default="ONLINE",
                        max_length=20,
                    ),
                ),
                ("placed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="addresses.address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="vendors.vendor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("IN_ZONE", "IN_ZONE"), ("OUT_OF_ZONE_SNAPP", "OUT_OF_ZONE_SNAPP")],
                        db_index=True,
                        default="IN_ZONE",
                        max_length=22,
                    ),
                ),
                ("is_cash_on_delivery", models.BooleanField(default=False)),
                ("courier_name", models.CharField(blank=True, default="", max_length=120)),
                ("courier_phone", models.CharField(blank=True, default="", max_length=32)),
                ("tracking_code", models.CharField(blank=True, default="", max_length=80)),
                ("tracking_url", models.URLField(blank=True, default="")),
                ("external_delivery_quote_amount", models.BigIntegerField(default=0)),
                ("external_delivery_final_amount", models.BigIntegerField(default=0)),
                ("external_provider", models.CharField(blank=True, default="", max_length=30)),
                ("external_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="delivery", to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, default="", max_length=20)),
                ("to_status", models.CharField(db_index=True, max_length=20)),
                (
                    "changed_by_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "SYSTEM"),
                            ("CUSTOMER", "CUSTOMER"),
                            ("VENDOR", "VENDOR"),
                            ("ADMIN", "ADMIN"),
                        ],
                        db_index=True,
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=250)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="orders.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_title_snapshot", models.CharField(max_length=250)),
                ("unit_price_snapshot", models.BigIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("modifiers", models.JSONField(blank=True, null=True)),
                ("line_subtotal", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="catalog.product"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="orderdelivery",
            index=models.Index(fields=["delivery_type", "created_at"], name="orders_order_delivery_type_9dc141_idx"),
        ),
        migrations.AddIndex(
            model_name="orderdelivery",
            index=models.Index(fields=["external_provider", "created_at"], name="orders_order_external_6eb0fc_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order", "created_at"], name="orders_order_order_i_958846_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["product"], name="orders_order_product_98e98f_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["vendor", "status", "placed_at"], name="orders_order_vendor__870f15_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "placed_at"], name="orders_order_user_id_3a351c_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["source", "placed_at"], name="orders_order_source_25cbf6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["payment_status", "placed_at"], name="orders_order_payment_2da9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(fields=["order", "created_at"], name="orders_order_order_i_b9fe8b_idx"),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(fields=["to_status", "created_at"], name="orders_order_to_stat_2717be_idx"),
        ),
    ]
