# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "TELEGRAM"),
                            ("SMS", "SMS"),
                            ("PAYMENT", "PAYMENT"),
                            ("DELIVERY", "DELIVERY"),
                            ("WEBHOOK", "WEBHOOK"),
                            ("ANALYTICS", "ANALYTICS"),
                            ("OTHER", "OTHER"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("base_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("credentials_ref", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "is_active"],
                        name="integrations_kind_9d0c24_idx",
                    ),
                    models.Index(fields=["code"], name="integrations_code_9d9fe9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IntegrationEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("path", models.CharField(blank=True, default="", max_length=240)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "code")},
                "indexes": [
                    models.Index(
                        fields=["provider", "is_active"],
                        name="integrations_provide_2f9f26_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorIntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_configs",
                        to="integrations.integrationprovider",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_configs",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "provider")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"],
                        name="integrations_vendor_i_46e86b_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="integrations_provide_1c7a22_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "UP"), ("DEGRADED", "DEGRADED"), ("DOWN", "DOWN")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "checked_at"],
                        name="integrations_provide_764503_idx",
                    ),
                    models.Index(
                        fields=["status", "checked_at"],
                        name="integrations_status_c61bea_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trace_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("request_url", models.CharField(blank=True, default="", max_length=500)),
                ("request_method", models.CharField(blank=True, default="", max_length=10)),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, db_index=True, null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "SUCCESS"),
                            ("FAIL", "FAIL"),
                            ("TIMEOUT", "TIMEOUT"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="integrations.integrationendpoint",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to="integrations.integrationprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_logs",
                        to="accounts.user",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_logs",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="integrations_create_d94ad2_idx"),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="integrations_provide_2357fe_idx",
                    ),
                    models.Index(
                        fields=["outcome", "created_at"], name="integrations_outcome__5a36f8_idx"
                    ),
                    models.Index(
                        fields=["response_status", "created_at"],
                        name="integrations_response_9e6ab1_idx",
                    ),
                    models.Index(fields=["trace_id", "created_at"], name="integrations_trace_id_0a819a_idx"),
                ],
            },
        ),
    ]
