# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=60)),
                ("receiver_name", models.CharField(blank=True, default="", max_length=120)),
                ("receiver_phone", models.CharField(blank=True, default="", max_length=20)),
                ("province", models.CharField(blank=True, default="", max_length=80)),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("street", models.CharField(blank=True, default="", max_length=240)),
                ("alley", models.CharField(blank=True, default="", max_length=240)),
                ("building", models.CharField(blank=True, default="", max_length=120)),
                ("plaque", models.CharField(blank=True, default="", max_length=30)),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("floor", models.CharField(blank=True, default="", max_length=30)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("full_text", models.TextField(blank=True, default="")),
                ("notes", models.CharField(blank=True, default="", max_length=240)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="addresses_a_user_id_86f40c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="addresses_a_user_id_833a5b_idx",
                    ),
                    models.Index(
                        fields=["city", "district"], name="addresses_a_city_e2778c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("is_active", models.BooleanField(default=True)),
                ("districts_csv", models.TextField(blank=True, default="")),
                (
                    "allow_out_of_zone",
                    models.BooleanField(default=True),
                ),
                (
                    "out_of_zone_policy",
                    models.CharField(
                        choices=[
                            ("SNAPP_COD", "SNAPP_COD"),
                            ("SNAPP_PREPAID", "SNAPP_PREPAID"),
                            ("DISALLOW", "DISALLOW"),
                        ],
                        default="SNAPP_COD",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AddressZoneMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_by",
                    models.CharField(
                        choices=[
                            ("DISTRICT", "DISTRICT"),
                            ("GEO", "GEO"),
                            ("MANUAL", "MANUAL"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        max_length=32,
                    ),
                ),
                ("matched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_match",
                        to="addresses.address",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="addresses.deliveryzone",
                    ),
                ),
            ],
        ),
    ]
