# Generated by Django 5.2.9 on 2025-12-24 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK'), ('OTHER', 'OTHER')], default='OTHER', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=120)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='تهران', max_length=80)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('address_line', models.TextField()),
                ('building', models.CharField(blank=True, default='', max_length=40)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('floor', models.CharField(blank=True, default='', max_length=40)),
                ('entrance', models.CharField(blank=True, default='', max_length=40)),
                ('doorbell', models.CharField(blank=True, default='', max_length=60)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('access_note', models.CharField(blank=True, default='', max_length=240)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_default', 'is_active'], name='addresses_a_user_id_77f20e_idx'), models.Index(fields=['city', 'is_active'], name='addresses_a_city_42e7fd_idx')],
            },
        ),
    ]
