# Generated by Django 5.0.7 on 2025-12-27 00:00
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=120, unique=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        max_length=10,
                    ),
                ),
                ("value_str", models.TextField(blank=True, default="")),
                ("value_int", models.BigIntegerField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="core_appset_key_a9e362_idx"),
                    models.Index(fields=["value_type"], name="core_appset_value_t_0d7750_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("rules", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="core_feature_code_7af821_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("image", "Image"), ("file", "File")],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("url", models.URLField(max_length=600)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset_type", "is_active", "created_at"],
                        name="core_mediaas_asset_t_4c15f6_idx",
                    ),
                ],
            },
        ),
    ]
