# Generated by Django 5.2.9 on 2025-12-24 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('vendor_type', models.CharField(choices=[('RESTAURANT', 'RESTAURANT'), ('CATERING', 'CATERING'), ('HOME_LICENSED', 'HOME_LICENSED')], default='CATERING', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(default='تهران', max_length=80)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=6.0, max_digits=6)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('accepts_preorder', models.BooleanField(default=False)),
                ('max_orders_per_hour', models.PositiveIntegerField(default=30)),
                ('allow_out_of_area_snap', models.BooleanField(default=True)),
                ('out_of_area_note', models.CharField(blank=True, default='ارسال خارج محدوده با اسنپ (پس\u200cکرایه)', max_length=240)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('sms_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'city'], name='vendors_ven_is_acti_4a0adb_idx'), models.Index(fields=['city', 'area'], name='vendors_ven_city_f6e221_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorMenuBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('variant_code', models.CharField(blank=True, default='', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_blocks', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vendors_ven_vendor__bca7d6_idx'), models.Index(fields=['item_id', 'variant_code', 'is_active'], name='vendors_ven_item_id_6b48fb_idx')],
                'unique_together': {('vendor', 'item_id', 'variant_code')},
            },
        ),
    ]
