# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_accepting_orders", models.BooleanField(default=True)),
                ("address_text", models.CharField(blank=True, default="", max_length=500)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                (
                    "primary_phone_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("telegram_chat_id", models.CharField(blank=True, default="", max_length=64)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("prep_time_minutes_default", models.PositiveSmallIntegerField(default=20)),
                ("min_order_amount", models.PositiveIntegerField(default=0)),
                ("max_active_orders", models.PositiveSmallIntegerField(default=0)),
                ("supports_in_zone_delivery", models.BooleanField(default=True)),
                ("supports_out_of_zone_snapp_cod", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delivery_zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vendors",
                        through="vendors.VendorDeliveryZone",
                        to="addresses.deliveryzone",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_visible", "is_accepting_orders"],
                        name="vendors_ven_is_acti_821d2c_idx",
                    ),
                    models.Index(fields=["slug"], name="vendors_ven_slug_7ed854_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        db_index=True,
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "weekday", "is_active"],
                        name="vendors_ven_vendor__6d2bf1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="main", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("address_text", models.CharField(blank=True, default="", max_length=500)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("service_radius_m", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"],
                        name="vendors_ven_vendor__2bf707_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "OWNER"),
                            ("MANAGER", "MANAGER"),
                            ("OPERATOR", "OPERATOR"),
                        ],
                        db_index=True,
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_roles",
                        to="accounts.user",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "user")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "role", "is_active"],
                        name="vendors_ven_vendor__da8cd3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VendorDeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_zones",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_zones",
                        to="addresses.deliveryzone",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "zone")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "zone", "is_active"],
                        name="vendors_ven_vendor__fdfaae_idx",
                    ),
                ],
            },
        ),
    ]
