# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, default="", max_length=140)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "name")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active", "sort_order"],
                        name="catalog_cat_vendor__2fe3cc_idx",
                    ),
                    models.Index(
                        fields=["vendor", "name"], name="catalog_cat_vendor__67fb63_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("is_required", models.BooleanField(default=False)),
                ("min_select", models.PositiveIntegerField(default=0)),
                ("max_select", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_groups",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "name")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active", "sort_order"],
                        name="catalog_opt_vendor__1c1efb_idx",
                    ),
                    models.Index(
                        fields=["vendor", "name"], name="catalog_opt_vendor__55eef8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fa", models.CharField(max_length=180)),
                ("name_en", models.CharField(blank=True, default="", max_length=180)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("short_description", models.CharField(blank=True, default="", max_length=240)),
                ("description", models.TextField(blank=True, default="")),
                ("base_price", models.BigIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("is_available_today", models.BooleanField(default=True)),
                ("min_qty", models.PositiveIntegerField(default=1)),
                ("max_qty", models.PositiveIntegerField(default=50)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "name_fa"), ("vendor", "slug")},
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active", "sort_order"],
                        name="catalog_pro_vendor__4fa42a_idx",
                    ),
                    models.Index(
                        fields=["vendor", "category", "is_active"],
                        name="catalog_pro_vendor__646533_idx",
                    ),
                    models.Index(
                        fields=["vendor", "name_fa"],
                        name="catalog_pro_vendor__773d51_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_rules",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "weekday", "is_active"],
                        name="catalog_pro_product__d5f7e6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, default="", max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "is_primary"],
                        name="catalog_pro_product__e5e8f2_idx",
                    ),
                    models.Index(
                        fields=["product", "sort_order"],
                        name="catalog_pro_product__0cf4ff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(blank=True, null=True)),
                ("min_select", models.PositiveIntegerField(blank=True, null=True)),
                ("max_select", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="catalog.optiongroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_option_groups",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "group")},
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "sort_order"],
                        name="catalog_pro_product__03f3d9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=120)),
                ("price_amount", models.BigIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "code")},
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "sort_order"],
                        name="catalog_pro_product__3a7fc0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=240)),
                ("price_delta_amount", models.BigIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.optiongroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "name")},
                "indexes": [
                    models.Index(
                        fields=["group", "is_active", "sort_order"],
                        name="catalog_opt_group_i_467f48_idx",
                    ),
                ],
            },
        ),
    ]
