# Generated by Django 5.2.9 on 2025-12-24 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name_fa', models.CharField(max_length=80)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_cat_is_acti_100145_idx')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(max_length=80, unique=True)),
                ('name_fa', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('price_toman', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.item')),
            ],
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price_toman', models.PositiveIntegerField()),
                ('new_price_toman', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='catalog.variant')),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active', 'is_published'], name='catalog_ite_categor_a9f503_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', 'is_published'], name='catalog_ite_is_acti_2469a2_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['item', 'is_active'], name='catalog_var_item_id_311c45_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['is_active'], name='catalog_var_is_acti_aad294_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('item', 'code')},
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['variant', 'changed_at'], name='catalog_pri_variant_a5414f_idx'),
        ),
    ]
