# Generated by Django 5.0.7 on 2025-12-27 00:00
import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("orders", "0001_initial"),
        ("accounts", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("telegram_chat_id", models.CharField(blank=True, default="", max_length=64)),
                ("phone_number", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["is_active"], name="notification_is_acti_cc0855_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "TELEGRAM"),
                            ("SMS", "SMS"),
                            ("EMAIL", "EMAIL"),
                            ("PUSH", "PUSH"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fa", "fa"), ("en", "en")],
                        db_index=True,
                        default="fa",
                        max_length=8,
                    ),
                ),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["channel", "is_active"],
                        name="notification_channel_1b1d4c_idx",
                    ),
                    models.Index(fields=["code"], name="notification_code_c864aa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("context", models.JSONField(blank=True, null=True)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "CUSTOMER"),
                            ("VENDOR", "VENDOR"),
                            ("ADMIN", "ADMIN"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "TELEGRAM"),
                            ("SMS", "SMS"),
                            ("EMAIL", "EMAIL"),
                            ("PUSH", "PUSH"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENDING", "SENDING"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(db_index=True, default=5)),
                ("scheduled_for", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="accounts.user",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notification_status_b96fcf_idx",
                    ),
                    models.Index(
                        fields=["channel", "status"],
                        name="notification_channel_1f04f9_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="notification_event_ty_961284_idx",
                    ),
                    models.Index(
                        fields=["recipient_type", "created_at"],
                        name="notification_recipient_11d6e1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_telegram_chat_id", models.CharField(blank=True, default="", max_length=64)),
                ("to_phone_number", models.CharField(blank=True, default="", max_length=32)),
                ("to_email", models.EmailField(blank=True, default="", max_length=254)),
                ("rendered_title", models.CharField(blank=True, default="", max_length=160)),
                ("rendered_body", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENDING", "SENDING"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_deliveries",
                        to="integrations.integrationendpoint",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_deliveries",
                        to="integrations.integrationprovider",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notification_status_e9b2fa_idx",
                    ),
                    models.Index(
                        fields=["provider", "status"],
                        name="notification_provider_2a464d_idx",
                    ),
                    models.Index(
                        fields=["notification", "attempt_no"],
                        name="notification_notifica_a5a93c_idx",
                    ),
                ],
            },
        ),
    ]
